language: node_js
env:
  global:
    - secure: aY4V9FcP+9993spYv2yqmalJDQ5g76XpI3vOcmbzza7ycHRXPTQy0Uevp8bh/yBXP4wAkak7axh+fW1sEJXs5Ui2WOPlMdO1XpfbsMcOXW3sp0tZIUWM53OZXltyHIvSndAkpQN3RRq1EsI7FI68i+ckwdUCzLhqfIvF7RJSo4Y=
    - secure: YJsQxD3G/lRmcAsAnWF1HYP2yYhmWZtWbiui1JR8XyMiyIpVYcwFsJUsf6mRZ/zR84XKiwtb7FClVkTrH4SIfkMhzGzXVv1yICopUEOJiV6cFr4twXtXFVTv0JGqBFLO2/fUeNqk6XWLRVkJUtKomG1ms5XD4aDh5JXwx/y0dKU=
