language: node_js
node_js:
  - "stable"
addons:
  sauce_connect:
    username:
      secure: "UGu1tUabPHdqCE+4dfFXWejkaEhmXvyUvmk4CBhoYJ62HvgNrVCaE0CZNRmKRqZTtNj1FKQiybiEh6LTe3/+06QdYywd2lmHaycCirBO+2nfA62WlgY/seHwJ5l9AOjjxdIauoZuPY4NySjdAEcxID495yo9DxyNvKTnJhnoXg4="
    access_key:
      secure: "jP3TUFS4NqnoclZuEzgVSzV6UYpi1pZfaORLygI6rFXO1Y8kg4i00JnkjwgDDMNuAT1MFC0MQwWPdO6WkhgG3bZEsaNUi55RF8InZXaqb8hT1qemrWduI7SSk0H2JHxIRisVDLh4wZT/hRN5kvZw/M60YI/dOL72XuT4IiF5RGk="
sudo: false
cache:
  directories:
    - node_modules
